
#### Data

*Welcome to the Art Insight App!!*

The Tate's dataset comprises metadata for approximately 70,000 artworks owned by the **Tate Art Museum** and jointly owned with the National Galleries of Scotland as part of the ARTIST ROOMS collection. This dataset offers insights into the diverse world of art, including details about the artworks themselves and around 3,500 associated artists. Released under the Creative Commons Public Domain CC0 license, the metadata is freely accessible for research and development purposes. It's important to note that images are not part of the dataset and have separate usage guidelines. While the dataset was last updated in October 2014 and may not receive ongoing updates, its availability provides a valuable snapshot of the Tate's collection for analysis, exploration, and research. Tate encourages users to acknowledge their usage and support future data efforts through attribution.

#### Purpose

The purpose of the provided Shiny app is to offer an interactive platform for exploring and analyzing various aspects of the world of art as follows:

1. The app provides detailed information about selected artworks.Users can learn about the titles, mediums, dimensions, and other important aspects of these artworks, **gaining a deeper understanding of each piece's significance**.

2. The app allows users to **actively engage by leaving comments and ratings on artworks**. This feature promotes a sense of community and interaction among users who can share their perspectives and insights.

3. The app not only unveils the distribution of **male and female artists across continents** but also unravels the **intricate threads of acquisition trends within each gender**. 
 
#### Creator

Amrita Jena (ajen0022@student.monash.edu)

<details>
<summary>Session information</summary>
```{r, echo = FALSE}
sessioninfo::session_info()
```
</details>
